os: unstable

install:
  - ps: Install-Product node 6.9
  - npm install -g flow-typed
  - yarn install

before_build:
  - yarn lint

build_script:
  - yarn compile

test_script:
  - yarn cover
  - yarn test:main

cache:
 - "%LOCALAPPDATA%\\Yarn"
